version: '2'
services:
  eureka-server:              #自定义服务名--注册中心
    restart: on-failure
    image: xmkj_registry         #镜像名称
    ports:
      - "8067:8067"            #映射的端口
    networks:
      - eureka-net             #网络模式
    environment:               #环境变量
      SERVER_PORT: "8067"      #自定义参数用于给服务的配置文件传递参数

#网关配置参考上面    
  gateway:
    restart: on-failure
    image: xmkj_gateway
    ports:
      - "8068:8068"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: "http://47.94.220.152:8067/eureka/"
      SERVER_PORT: "8067"
    networks:
      - eureka-net
      
#网关配置参考上面    
  uua:
    restart: on-failure
    image: xmkj_uua
    ports:
      - "8069:8069"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: "http://47.94.220.152:8067/eureka/"
      SERVER_PORT: "8069"
      SPRING_REDIS_DATABASE: "0"
      SPRING_REDIS_HOST: "47.94.216.196"
      SPRING_REDIS_PORT: "6379"
    networks:
      - eureka-net   
networks:
  eureka-net:
    driver: bridge