server:
  port: 8069
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8067/eureka/
spring:
  application:
    name: Uaa
  redis:
    database: 0
    host: 47.94.216.196
    port: 6211
    password: lmkj@wxcde
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.216.196:3306/lmkj_uua?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: lmkj@1234
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
mybatis-plus:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  typeAliasesPackage: com.zz.xmkj.domain
  global-config:
    db-config:
      db-type: mysql
      
short-message:
  access-key-id: LTAI4GKsjeNRPnCAyniMMKn8
  access-key-secret: 0jfDOjlDQEfb71IdGi1tvjaVJ5ts2D
  template-code: SMS_202390236
  sign-name: 湖南留铭科技有限公司     
      
swagger:
  enable: true
  
initCaches:
  userMenuCache: 3600s  