server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: fsh-uaa
        uri: lb://UAA
        predicates:
        - Path=/UAA/**    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8067/eureka/
security:
  oauth2:
    client:
      access-token-uri: http://UAA/oauth/token
      user-authorization-uri: http://UAA/oauth/authorize
    resource:
      user-info-uri: http://UAA/user
      prefer-token-info: false
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug      